config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/top'
  root to: "homes#top"
  get 'home/about', to: 'homes#about', as: 'about'
  resources :users, only: [:show, :edit, :update, :index]
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_one_attached :profile_image
    has_many :books, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id, notice: 'Signed in successfully.')
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end 

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:home, :about, :new, :create]

  def new
    @book = Book.new
  end

  def create
    @books =Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] = "Book create successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    is_matching_login_user
    @book = Book.find(params[:id])
  end

  def update
    is_matching_login_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "Book updated successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end

  private

 def is_matching_login_user
  book = Book.find(params[:id])
  unless book.user_id == current_user.id
    redirect_to books_path
  end
 end



  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:home, :about, :new, :create]

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "User updated successfully."
       redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  private

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>New book</h2>
<%= form_with model: book, url: books_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <%= form.submit "Create Book" %>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <% if user_signed_in? %>
         <%= render "users/user_info", user: current_user %>
        <% end %>
      </div>
      <div class="col-md-9">
        <h2>Editing Book</h2>
        <%= form_with model: @book, url: book_path(@book), method: :patch do |form| %>
          <div>
            <%= form.label :title %>
            <%= form.text_field :title %>
          </div>
          <div>
            <%= form.label :body %>
            <%= form.text_area :body %>
          </div>
          <%= form.submit "Update Book" %>
          <%= link_to "Show", book_path(@book) %> | <%= link_to "Back to Books", books_path %>
        <% end %>
      </div>
    </div>
  </div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1">
      <%= render "users/user_info", user: @user %>
      <%= render "books/new", book: @book %>
    </div>
    <div class="col-md-9">
      <h1>Books</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to image_tag(book.user.get_profile_image(50, 50), class: "profile-image"), user_path(book.user) %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/user_info", user: @user %>
      <%= render "books/new", book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td><%= link_to image_tag(@book.user.get_profile_image(100, 100), class: "profile-image"), user_path(@book.user) %></td>
            <td><%= link_to @book.user.name, user_path(@book.user) %></td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <% if current_user == @book.user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger destroy_book_#{@book.id}", data: { confirm: "本当に消しますか？" } %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h1 class="text-center mt-5">Welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>!</h1>
        <p class="text-center mt-3">In Bookers, you can share and exchange your opinions, impressions, and emotions about various books!</p>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>Welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>,</p>
        
          <p>you can share and exchange your opinions, impressions, and emotions</p>
          <p>about various books!</p>
        
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/079d0f24e7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Bookers2", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to user_path(current_user.id), class: "nav-link" do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to users_path, class: "nav-link" do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: "nav-link" do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
       <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link" do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to about_path, class: "nav-link" do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link" do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>


   <main>
    <% if flash[:notice].present? %>
    <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>

   </main>
　</body>
</html>

app/views/users/_user_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100, 100), class: "profile-image" %>
  <table class="table">
    <tbody>
      <tr>
        <th>Name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>Introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

    <div class="row">
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary" do %>
        <i class="fas fa-user-cog" aria-hidden="true"></i>
      <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h1>User info</h1>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id: "inputName", placeholder: "Name", class: "form-control" %>
      </div>

      <div class="form-group">
        <label for="UserImage">Image</label>
          <input class="form-control-file user_image" accept="image/*" type="file" name="user[profile_image]" id="user_profile_image">
      </div>

      <div class="form-group">
        <label for="inputIntroduction">Introduction</label>
        <%= f.text_field :introduction, id: "inputIntroduction", placeholder: "Introduction", class: "form-control" %>
      </div>

      <%= f.submit "Update User", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1">
      <%= render "users/user_info", user: @user %>
      <%= render "books/new", book: @book %>
    </div>

    <div class="col-md-9">
      <h1>Users</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(50, 50), class: "profile-image" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1">
      <%= render "users/user_info", user: @user %>
      <%= render "books/new", book: @book %>
    </div>
    <div class="col-md-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% if @user.books.any? %>
            <% @user.books.each do |book| %>
              <tr>
                <td>
                  <a href="<%= user_path(book.user) %>">
                    <%= image_tag(book.user.get_profile_image(100, 100)) %>
                  </a>
                </td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="3">No books found.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>